# .github/FUNDING.yml
# Official GitHub funding links - these are the only supported platforms

github: [jblais493]  # Can list multiple: [user1, user2]
buy_me_a_coffee: joshuablais
ko_fi: joshuablais
liberapay: joshuablais
