themes:
  - name: "compline"
    colors:
      - "#1a1d21"
      - "#22262b"
      - "#0f1114"
      - "#171a1e"
      - "#1f2228"
      - "#282c34"
      - "#3d424a"
      - "#515761"
      - "#676d77"
      - "#8b919a"
      - "#e0dcd4"
      - "#e0dcd4"
      - "#c0bdb8"
      - "#c8beb8"
      - "#c8c0b0"
      - "#b4beb4"
      - "#b4bec8"
      - "#ccc4b0"
      - "#c4beb8"
      - "#b0c0b8"
      - "#9ca8b4"
