format = """
[░▒▓](#e0dcd4)\
[ ✙ ](bg:#e0dcd4 fg:#1a1d21)\
[](bg:#282c34 fg:#e0dcd4)\
$directory\
[](fg:#282c34 bg:#3d424a)\
$git_branch\
$git_status\
[](fg:#3d424a bg:#515761)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#515761 bg:#e0dcd4)\
$time\
[](fg:#e0dcd4)\
\n$character"""

[directory]
style = "fg:#ccc4b4 bg:#282c34"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#515761"
format = '[[ $symbol $branch ](fg:#b4c0c8 bg:#3d424a)]($style)'

[git_status]
style = "bg:#3B4252"
format = '[[($all_status$ahead_behind )](fg:#b4c0c8 bg:#3d424a)]($style)'

[nodejs]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[rust]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[golang]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#b8c4b8 bg:#515761)]($style)'

[php]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2e2e2e"
format = '[[  $time ](fg:#1a1d21 bg:#e0dcd4)]($style)'
